### ISSUE TITLE
Improve Maven dependency snapshotting by categorising dependencies into distribution, test, and build

### ISSUE THREAD

**Issue by lolski** [graknlabs/dependencies#244]
# Description

We need to improve our Maven dependency snapshot by categorising them into three categories:

1. `artifacts-distribution.snapshot`: the dependencies that get included in the distribution. For example, for Grakn Core it would be the zip and tar distribution and for Client Java the Maven JAR.
2. `artifacts-test.snapshot`: dependencies that are used in tests (eg., JUnit, GraknCoreRunner, Cucumber), minus the dependencies in `artifacts-distribution.snapshot`. (ps: Could this be sufficiently implemented by querying for  all dependencies of `java_test` targets??)
3. `artifacts-build.snapshot`: the rest of the dependencies, that are not in `artifact-distribution.snapshot` or `artifact-test.snapshot`.

They should be generated in the same way as the old one, eg., when the user invokes `update.sh`:

```
$ ./dependencies/maven/update.sh assemble-mac-zip, assemble-linux-targz, assemble-windows-zip
Regenerating new snapshot files from WORKSPACE...
DONE!
'artifacts-distribution.snapshot' refreshed: 3 dependencies added, 1 dependencies removed.
Added dependencies:
- @maven//a
- @maven//b
- @maven//c
Removed dependencies:
- @maven//d

'artifacts-test.snapshot' refreshed: 0 dependencies added, 0 dependencies removed.
'artifacts-build.snapshot' refreshed: 0 dependencies added, 0 dependencies removed.
```

**Comment by haikalpribadi** [comment]
Covered by: https://github.com/graknlabs/dependencies/issues/226
